// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnlkbtnwibeblbnxkvcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubGtidG53aWJlYmxibnhrdmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTYxNTMsImV4cCI6MjA2OTE3MjE1M30.LIiAKdEa6Bjd8y4ZD9dOyG-L58oqsbRyAuPvHWtdKyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});